// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxNcKYv-pVCuiGUMZnTzpMCbPjWcG0o_k',
    appId: '1:73965937301:web:673f96bbf650cf0901b19c',
    messagingSenderId: '73965937301',
    projectId: 'whiskyapp-8e2a2',
    authDomain: 'whiskyapp-8e2a2.firebaseapp.com',
    storageBucket: 'whiskyapp-8e2a2.appspot.com',
    measurementId: 'G-KFXLD39XQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWoD8_K70K2LgXLUS2oLO7Rzh8AGTnD-s',
    appId: '1:73965937301:android:a99bf34401757a8a01b19c',
    messagingSenderId: '73965937301',
    projectId: 'whiskyapp-8e2a2',
    storageBucket: 'whiskyapp-8e2a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDnKbemxrTmuQk8MREBh4ULl-qsc9A8UM',
    appId: '1:73965937301:ios:6149dca96cacf4f401b19c',
    messagingSenderId: '73965937301',
    projectId: 'whiskyapp-8e2a2',
    storageBucket: 'whiskyapp-8e2a2.appspot.com',
    androidClientId: '73965937301-j60hmq6ne8ktppksr8peuffkjm6tsovn.apps.googleusercontent.com',
    iosClientId: '73965937301-1o7a99mnvclqp0fjph3l11efhp0pvi1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.whiskyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDnKbemxrTmuQk8MREBh4ULl-qsc9A8UM',
    appId: '1:73965937301:ios:6149dca96cacf4f401b19c',
    messagingSenderId: '73965937301',
    projectId: 'whiskyapp-8e2a2',
    storageBucket: 'whiskyapp-8e2a2.appspot.com',
    androidClientId: '73965937301-j60hmq6ne8ktppksr8peuffkjm6tsovn.apps.googleusercontent.com',
    iosClientId: '73965937301-1o7a99mnvclqp0fjph3l11efhp0pvi1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.whiskyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxNcKYv-pVCuiGUMZnTzpMCbPjWcG0o_k',
    appId: '1:73965937301:web:98f217f6be85ef1101b19c',
    messagingSenderId: '73965937301',
    projectId: 'whiskyapp-8e2a2',
    authDomain: 'whiskyapp-8e2a2.firebaseapp.com',
    storageBucket: 'whiskyapp-8e2a2.appspot.com',
    measurementId: 'G-73DY832SK2',
  );
}
